### ISSUE TITLE
Issue 1: Set up project folder for Eliza Chatbot

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#10]
**Description**
Create a new project folder in 'emergingtechnologies' repository and initiliaze it with necessary  files.

**Tasks**
- [x] Create a project folder
- [x] Add `index.html`, `style.css`, `eliza.js`, and `README.md`.
- [ ] Write a basic project description in `README.md`.
- [x] Set up GitHub Pages and add a GitHub Action to deploy the `main` branch to GitHub Pages.
