### ISSUE TITLE
Issue 2: Create the HTML structure for the chatbot interface

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#11]
**Description:**

**Tasks:**

- [x] Set up a basic HTML structure in index.html.
- [x] Add a div or similar element for displaying the conversation history.
- [x] Add a textarea or input element for user input.
- [x] Add a submit button to send the message.
