### ISSUE TITLE
Issue 3: Style the Interface with CSS

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#12]
**Description:**
Create a user-friendly layout for the chatbot interface.

**Tasks**
- [x] Style the conversation history section in style.css.
- [x] Style the user input box and submit button.
- [x]  Make the layout responsive for different screen sizes. _(optional)_
