### ISSUE TITLE
Issue 6: Add Basic Response Patterns

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#15]
**Description:**
Expand the chatbot's response patterns to simulate meaningful conversations.

**Tasks:**
- [ ] Implement basic patterns for common phrases. For example: "I feel", "I think" and so on.
- [ ] Add responses to other keywords that might be common in user input.
- [ ] Test to ensure that ELIZA responds appropriately based on input patterns.
