### ISSUE TITLE
Issue 7: Document Project in README.md

### ISSUE THREAD

**Issue by JakubSzkup1** [JakubSzkup1/emergingtechnologies#16]
**Description:**
Provide a description of the project, instructions for usage, and a link to the GitHub Pages deployment.

**Tasks:**
- [ ]  Write a clear project description in README.md.
- [ ]  Include instructions on how to use the chatbot.
- [ ] Add a link to the deployed GitHub Pages site.
